/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.sound.sampled.*;
/**
 *
 * @author lufer
 */
public class PerfilProfesor extends javax.swing.JFrame {

    //Esta variable es el usuario que ingreso, de ahi se obtienen los datos necesarios
    private Profesor usuario;
    TablaPerfilProfesor tablaCalificaciones;

    /**
     * Creates new form PerfilProfesor
     */
    public PerfilProfesor() {
        initComponents();
    }

    public PerfilProfesor(Profesor usuario) {
        this.usuario = usuario;
        initComponents();
        tablaCalificaciones = new TablaPerfilProfesor();
        try {
            tablaCalificaciones = new TablaPerfilProfesor(usuario, jComboBoxMateria.getSelectedItem().toString());
        } catch (Exception ex) {
            jComboBoxMateria.addItem("No hay grupo");
        }
        jScrollPaneCalificaciones.setViewportView(tablaCalificaciones.table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProfesor = new javax.swing.JTabbedPane();
        panelInformacion = new javax.swing.JPanel();
        jLabelTituloInformacion = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelRfc = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        espacioNombre = new javax.swing.JLabel();
        espacioRfc = new javax.swing.JLabel();
        espacioEdad = new javax.swing.JLabel();
        espacioGenero = new javax.swing.JLabel();
        jLabelTextGrupo = new javax.swing.JLabel();
        espacioGrupo = new javax.swing.JLabel();
        btnCerrarInformacion = new javax.swing.JButton();
        panelCalificaciones = new javax.swing.JPanel();
        jLabelTituloCalificaciones = new javax.swing.JLabel();
        jLabelTextoEscoger = new javax.swing.JLabel();
        jComboBoxMateria = new javax.swing.JComboBox<>();
        jScrollPaneCalificaciones = new javax.swing.JScrollPane();
        btnCerrarCalificaciones = new javax.swing.JButton();
        panelConfiguracion = new javax.swing.JPanel();
        jLabelTituloConfiguracion = new javax.swing.JLabel();
        jLabelTextoContrasena = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        btnCerrarSesionProfesor = new javax.swing.JButton();
        btnCerrarConfiguracion = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelInformacion.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloInformacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloInformacion.setText("Bienvenido profesor");

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNombre.setText("Nombre completo:");

        jLabelRfc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelRfc.setText("RFC:");

        jLabelEdad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEdad.setText("Edad:");

        jLabelGenero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelGenero.setText("Genero:");

        espacioNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        espacioNombre.setText(usuario.getNombres()+" "+usuario.getApPaterno()+" "+usuario.getApMaterno());

        espacioRfc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        espacioRfc.setText(usuario.getId());

        espacioEdad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        espacioEdad.setText(String.valueOf(usuario.getEdad()+" años"));

        espacioGenero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        espacioGenero.setText(String.valueOf(usuario.getGenero()));

        jLabelTextGrupo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextGrupo.setText("Grupo:");

        espacioGrupo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnCerrarInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarInformacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarInformacion)
                .addContainerGap())
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelInformacionLayout.createSequentialGroup()
                            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(95, 95, 95)
                            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(espacioRfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(espacioEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(espacioGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(espacioGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelInformacionLayout.createSequentialGroup()
                            .addComponent(jLabelNombre)
                            .addGap(18, 18, 18)
                            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTituloInformacion)
                                .addComponent(espacioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarInformacion))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(espacioNombre))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addComponent(espacioRfc)
                        .addGap(18, 18, 18)
                        .addComponent(espacioEdad))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelRfc)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEdad)))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGenero)
                    .addComponent(espacioGenero))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(espacioGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextGrupo))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        String grupo;
        try{
            if(usuario.getGrupo().equals("")){
                grupo = "No cuentas con un grupo asignado";
            }else{
                grupo = usuario.getGrupo();
            }
        }catch(Exception ex){
            grupo = "No cuentas con un grupo asignado";;
        }
        espacioGrupo.setText(grupo);

        jTabbedPaneProfesor.addTab("Información", panelInformacion);

        panelCalificaciones.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloCalificaciones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloCalificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloCalificaciones.setText("Bienvenido profesor");

        jLabelTextoEscoger.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextoEscoger.setText("Escoger materia");

        ArrayList<String> materias = SentenciasSQL.materiasGrupo(usuario.getGrupo());
        for (String m : materias) {
            jComboBoxMateria.addItem(m);
        }
        jComboBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMateriaActionPerformed(evt);
            }
        });

        btnCerrarCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCalificacionesbtnCerrarInformacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCalificacionesLayout = new javax.swing.GroupLayout(panelCalificaciones);
        panelCalificaciones.setLayout(panelCalificacionesLayout);
        panelCalificacionesLayout.setHorizontalGroup(
            panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalificacionesLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jLabelTituloCalificaciones)
                .addGap(124, 124, 124)
                .addComponent(btnCerrarCalificaciones)
                .addContainerGap())
            .addGroup(panelCalificacionesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCalificacionesLayout.createSequentialGroup()
                        .addComponent(jLabelTextoEscoger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelCalificacionesLayout.setVerticalGroup(
            panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalificacionesLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTituloCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarCalificaciones))
                .addGap(18, 18, 18)
                .addGroup(panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoEscoger)
                    .addComponent(jComboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPaneCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPaneProfesor.addTab("Calificaciones", panelCalificaciones);

        panelConfiguracion.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloConfiguracion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloConfiguracion.setText("Bienvenido profesor");

        jLabelTextoContrasena.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextoContrasena.setText("Contraseña:");

        btnCambiar.setBackground(new java.awt.Color(0, 0, 153));
        btnCambiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiar.setText("CAMBIAR");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnCerrarSesionProfesor.setBackground(new java.awt.Color(153, 0, 0));
        btnCerrarSesionProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCerrarSesionProfesor.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesionProfesor.setText("CERRAR SESION");
        btnCerrarSesionProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionProfesorActionPerformed(evt);
            }
        });

        btnCerrarConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarConfiguracionbtnCerrarInformacionActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ojo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfiguracionLayout = new javax.swing.GroupLayout(panelConfiguracion);
        panelConfiguracion.setLayout(panelConfiguracionLayout);
        panelConfiguracionLayout.setHorizontalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTituloConfiguracion)
                        .addGap(117, 117, 117)
                        .addComponent(btnCerrarConfiguracion))
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelTextoContrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrarSesionProfesor)
                            .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelConfiguracionLayout.setVerticalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTituloConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarConfiguracion))
                .addGap(18, 18, 18)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTextoContrasena)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(244, 244, 244)
                .addComponent(btnCerrarSesionProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPaneProfesor.addTab("Configuración", panelConfiguracion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProfesor)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        String contra = txtContrasena.getText();
        usuario.setContrasena(contra, "Profesor", "rfc");
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void jComboBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMateriaActionPerformed
        tablaCalificaciones = new TablaPerfilProfesor(usuario, jComboBoxMateria.getSelectedItem().toString());
        jScrollPaneCalificaciones.setViewportView(tablaCalificaciones.table);
    }//GEN-LAST:event_jComboBoxMateriaActionPerformed
    //Cierra la sesion mandando a Inicio
    private void btnCerrarSesionProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionProfesorActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar1.wav")));clip.start();}
            catch(Exception e){}
        JOptionPane.showMessageDialog(null,"SESION CERRADA.","EXITO",JOptionPane.INFORMATION_MESSAGE);
        
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionProfesorActionPerformed

    private void btnCerrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarInformacionActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarInformacionActionPerformed

    private void btnCerrarCalificacionesbtnCerrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCalificacionesbtnCerrarInformacionActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarCalificacionesbtnCerrarInformacionActionPerformed

    private void btnCerrarConfiguracionbtnCerrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarConfiguracionbtnCerrarInformacionActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarConfiguracionbtnCerrarInformacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtContrasena.echoCharIsSet()){txtContrasena.setEchoChar((char)0);}
        else{txtContrasena.setEchoChar('*');}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCerrarCalificaciones;
    private javax.swing.JButton btnCerrarConfiguracion;
    private javax.swing.JButton btnCerrarInformacion;
    private javax.swing.JButton btnCerrarSesionProfesor;
    private javax.swing.JLabel espacioEdad;
    private javax.swing.JLabel espacioGenero;
    private javax.swing.JLabel espacioGrupo;
    private javax.swing.JLabel espacioNombre;
    private javax.swing.JLabel espacioRfc;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxMateria;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRfc;
    private javax.swing.JLabel jLabelTextGrupo;
    private javax.swing.JLabel jLabelTextoContrasena;
    private javax.swing.JLabel jLabelTextoEscoger;
    private javax.swing.JLabel jLabelTituloCalificaciones;
    private javax.swing.JLabel jLabelTituloConfiguracion;
    private javax.swing.JLabel jLabelTituloInformacion;
    private javax.swing.JScrollPane jScrollPaneCalificaciones;
    private javax.swing.JTabbedPane jTabbedPaneProfesor;
    private javax.swing.JPanel panelCalificaciones;
    private javax.swing.JPanel panelConfiguracion;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables
    public Person getUsuario() {
        return usuario;
    }

    public void setUsuario(Profesor usuario) {
        this.usuario = usuario;
    }
}
