/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.sound.sampled.*;
/**
 *
 * @author lufer
 */
public class PerfilAdministrador extends javax.swing.JFrame {

    private final Administrador admin;
    TablaAdminAlumno tablaDatosAlumnos;
    TablaAdminProfesor tablaDatosProfesores;
    TablaAdminGT tablaGT;
    TablaAdminGI tablaGI;

    /**
     * Creates new form PerfilAdministrador
     */
    public PerfilAdministrador() {

        admin = new Administrador();

        initComponents();
        //Rellena los combobox con los grados
        this.setjBoxGrados();
        //pone todos los datos en las tablas
        this.actualizarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAPG = new javax.swing.JTabbedPane();
        panelAT = new javax.swing.JPanel();
        jLabelTituloAT = new javax.swing.JLabel();
        jScrollPaneAT = new javax.swing.JScrollPane();
        jLabelRecuerdaAT = new javax.swing.JLabel();
        jLabelAgregarAGrupoAT = new javax.swing.JLabel();
        jComboBoxGruposAT = new javax.swing.JComboBox<>();
        btnGuardarAT = new javax.swing.JButton();
        jLabelElminarADeGrupoAT = new javax.swing.JLabel();
        btnEliminarADeGrupoAT = new javax.swing.JButton();
        jLabelRemplazoAT = new javax.swing.JLabel();
        jLabelAlumnoBajaAT = new javax.swing.JLabel();
        btnBajaAlumnoAT = new javax.swing.JButton();
        jComboBoxGradoAT = new javax.swing.JComboBox<>();
        jLabelBuscarElemAE1 = new javax.swing.JLabel();
        txtCurpAT = new javax.swing.JTextField();
        btnCerrarAT = new javax.swing.JButton();
        panelPT = new javax.swing.JPanel();
        jLabelTituloPT = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPanePT = new javax.swing.JScrollPane();
        jLabelRecuerdaPT = new javax.swing.JLabel();
        jLabelAgregarAGrupoPT = new javax.swing.JLabel();
        jComboBoxGradoPT = new javax.swing.JComboBox<>();
        jComboBoxGruposPT = new javax.swing.JComboBox<>();
        btnGuardarPT = new javax.swing.JButton();
        jLabelRemplazoPT = new javax.swing.JLabel();
        jLabelElminarPDeGrupoPT = new javax.swing.JLabel();
        btnEliminarPDeGrupoPT = new javax.swing.JButton();
        jLabelProfesorBajaPT = new javax.swing.JLabel();
        btnBajaProfesorPT = new javax.swing.JButton();
        jLabelBuscarElem = new javax.swing.JLabel();
        txtRfcPT = new javax.swing.JTextField();
        btnCerrarPT = new javax.swing.JButton();
        jTabbedPaneGTIA = new javax.swing.JTabbedPane();
        panelGT = new javax.swing.JPanel();
        jLabeTituloGT = new javax.swing.JLabel();
        jScrollPaneGT = new javax.swing.JScrollPane();
        jLabelEliminarGrupoGT = new javax.swing.JLabel();
        btnEliminarGrupoGT = new javax.swing.JButton();
        jLabelRemplazoPE1 = new javax.swing.JLabel();
        btnCerrarGT = new javax.swing.JButton();
        panelGI = new javax.swing.JPanel();
        jLabelTituloGI = new javax.swing.JLabel();
        jScrollPaneGI = new javax.swing.JScrollPane();
        jLabelProfesorGrupoGI = new javax.swing.JLabel();
        jLabelNomProfesorGI = new javax.swing.JLabel();
        jLabelBuscarGrupoGI = new javax.swing.JLabel();
        jComboBoxGradoGI = new javax.swing.JComboBox<>();
        jComboBoxGruposGI = new javax.swing.JComboBox<>();
        btnCerrarGI = new javax.swing.JButton();
        panelGA = new javax.swing.JPanel();
        jLabelTituloGA = new javax.swing.JLabel();
        btnCerrarSesionAdmin = new javax.swing.JButton();
        jLabelElegirGradoGA = new javax.swing.JLabel();
        jComboBoxGradoGA = new javax.swing.JComboBox<>();
        jLabelNombreGrupoGA = new javax.swing.JLabel();
        txtNombreGrupo = new javax.swing.JTextField();
        btnGuardarGA = new javax.swing.JButton();
        btnCerrarGA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelAT.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloAT.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloAT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloAT.setText("Administrador");

        jLabelRecuerdaAT.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRecuerdaAT.setText("*Recuerda seleccionar el elemento para ejecutar los cambios.");

        jLabelAgregarAGrupoAT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAgregarAGrupoAT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarAGrupoAT.setText("Agregar a grupo por grado:");

        jComboBoxGruposAT.setToolTipText("");
        jComboBoxGruposAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGruposATActionPerformed(evt);
            }
        });

        btnGuardarAT.setBackground(new java.awt.Color(0, 0, 153));
        btnGuardarAT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnGuardarAT.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarAT.setText("GUARDAR");
        btnGuardarAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarATActionPerformed(evt);
            }
        });

        jLabelElminarADeGrupoAT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelElminarADeGrupoAT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelElminarADeGrupoAT.setText("Eliminar de su grupo:");

        btnEliminarADeGrupoAT.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarADeGrupoAT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnEliminarADeGrupoAT.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarADeGrupoAT.setText("ELIMINAR");
        btnEliminarADeGrupoAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarADeGrupoATActionPerformed(evt);
            }
        });

        jLabelRemplazoAT.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRemplazoAT.setText("*Si el alumno tiene un curso actualmente será remplazado.");

        jLabelAlumnoBajaAT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAlumnoBajaAT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlumnoBajaAT.setText("Dar alumno de baja:");

        btnBajaAlumnoAT.setBackground(new java.awt.Color(153, 0, 0));
        btnBajaAlumnoAT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnBajaAlumnoAT.setForeground(new java.awt.Color(255, 255, 255));
        btnBajaAlumnoAT.setText("ELIMINAR");
        btnBajaAlumnoAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaAlumnoATActionPerformed(evt);
            }
        });

        jComboBoxGradoAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGradoATActionPerformed(evt);
            }
        });

        jLabelBuscarElemAE1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelBuscarElemAE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscarElemAE1.setText("Buscar por CURP:");

        txtCurpAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpATActionPerformed(evt);
            }
        });
        txtCurpAT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCurpATKeyReleased(evt);
            }
        });

        btnCerrarAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelATLayout = new javax.swing.GroupLayout(panelAT);
        panelAT.setLayout(panelATLayout);
        panelATLayout.setHorizontalGroup(
            panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelATLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAT, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRecuerdaAT)
                    .addGroup(panelATLayout.createSequentialGroup()
                        .addComponent(jLabelAgregarAGrupoAT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGradoAT, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxGruposAT, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarAT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelATLayout.createSequentialGroup()
                            .addComponent(jLabelElminarADeGrupoAT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                            .addComponent(btnEliminarADeGrupoAT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelRemplazoAT)
                        .addGroup(panelATLayout.createSequentialGroup()
                            .addComponent(jLabelAlumnoBajaAT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBajaAlumnoAT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelATLayout.createSequentialGroup()
                        .addComponent(jLabelBuscarElemAE1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCurpAT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(panelATLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabelTituloAT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarAT)
                .addGap(18, 18, 18))
        );
        panelATLayout.setVerticalGroup(
            panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelATLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloAT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurpAT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscarElemAE1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRecuerdaAT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAgregarAGrupoAT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGruposAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarAT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGradoAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRemplazoAT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarADeGrupoAT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelElminarADeGrupoAT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBajaAlumnoAT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlumnoBajaAT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        jTabbedPaneAPG.addTab("Alumnos", panelAT);

        panelPT.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloPT.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloPT.setText("Administrador");

        jLabelRecuerdaPT.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRecuerdaPT.setText("*Recuerda seleccionar el elemento para ejecutar los cambios.");

        jLabelAgregarAGrupoPT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAgregarAGrupoPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarAGrupoPT.setText("Agregar a grupo por grado:");

        jComboBoxGradoPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGradoPTActionPerformed(evt);
            }
        });

        jComboBoxGruposPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGruposPTActionPerformed(evt);
            }
        });

        btnGuardarPT.setBackground(new java.awt.Color(0, 0, 153));
        btnGuardarPT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnGuardarPT.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPT.setText("GUARDAR");
        btnGuardarPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPTActionPerformed(evt);
            }
        });

        jLabelRemplazoPT.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRemplazoPT.setText("*Si el alumno tiene un curso actualmente será remplazado.");

        jLabelElminarPDeGrupoPT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelElminarPDeGrupoPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelElminarPDeGrupoPT.setText("Eliminar de su grupo:");

        btnEliminarPDeGrupoPT.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarPDeGrupoPT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnEliminarPDeGrupoPT.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPDeGrupoPT.setText("ELIMINAR");
        btnEliminarPDeGrupoPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPDeGrupoPTActionPerformed(evt);
            }
        });

        jLabelProfesorBajaPT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelProfesorBajaPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfesorBajaPT.setText("Dar profesor de baja:");

        btnBajaProfesorPT.setBackground(new java.awt.Color(153, 0, 0));
        btnBajaProfesorPT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnBajaProfesorPT.setForeground(new java.awt.Color(255, 255, 255));
        btnBajaProfesorPT.setText("ELIMINAR");
        btnBajaProfesorPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaProfesorPTActionPerformed(evt);
            }
        });

        jLabelBuscarElem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelBuscarElem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscarElem.setText("Buscar por RFC:");

        txtRfcPT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRfcPTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRfcPTFocusLost(evt);
            }
        });
        txtRfcPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcPTActionPerformed(evt);
            }
        });
        txtRfcPT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRfcPTKeyReleased(evt);
            }
        });

        btnCerrarPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarPTbtnCerrarATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPTLayout = new javax.swing.GroupLayout(panelPT);
        panelPT.setLayout(panelPTLayout);
        panelPTLayout.setHorizontalGroup(
            panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPTLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPTLayout.createSequentialGroup()
                        .addComponent(jLabelBuscarElem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRfcPT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPTLayout.createSequentialGroup()
                            .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelPTLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(686, 686, 686))
                                .addComponent(jScrollPanePT, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27))
                        .addGroup(panelPTLayout.createSequentialGroup()
                            .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelPTLayout.createSequentialGroup()
                                    .addComponent(jLabelTituloPT)
                                    .addGap(236, 236, 236)
                                    .addComponent(btnCerrarPT))
                                .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panelPTLayout.createSequentialGroup()
                                            .addComponent(jLabelElminarPDeGrupoPT)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                                            .addComponent(btnEliminarPDeGrupoPT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelRemplazoPT)
                                        .addGroup(panelPTLayout.createSequentialGroup()
                                            .addComponent(jLabelProfesorBajaPT)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnBajaProfesorPT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelRecuerdaPT)
                                    .addGroup(panelPTLayout.createSequentialGroup()
                                        .addComponent(jLabelAgregarAGrupoPT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxGradoPT, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxGruposPT, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardarPT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap(20, Short.MAX_VALUE)))))
        );
        panelPTLayout.setVerticalGroup(
            panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloPT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarPT))
                .addGap(18, 18, 18)
                .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscarElem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRfcPT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRecuerdaPT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAgregarAGrupoPT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGruposPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarPT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGradoPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRemplazoPT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarPDeGrupoPT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelElminarPDeGrupoPT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBajaProfesorPT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProfesorBajaPT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jLabel25)
                .addGap(32, 32, 32))
        );

        jTabbedPaneAPG.addTab("Profesores", panelPT);

        panelGT.setBackground(new java.awt.Color(153, 153, 255));

        jLabeTituloGT.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabeTituloGT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeTituloGT.setText("Administrador");

        jLabelEliminarGrupoGT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEliminarGrupoGT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminarGrupoGT.setText("Eliminar grupo:");

        btnEliminarGrupoGT.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarGrupoGT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnEliminarGrupoGT.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarGrupoGT.setText("ELIMINAR");
        btnEliminarGrupoGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGrupoGTActionPerformed(evt);
            }
        });

        jLabelRemplazoPE1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRemplazoPE1.setText("*Si el grupo tiene asignados alumnos o un profesor los dejará sin grupo ");

        btnCerrarGT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarGTbtnCerrarATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGTLayout = new javax.swing.GroupLayout(panelGT);
        panelGT.setLayout(panelGTLayout);
        panelGTLayout.setHorizontalGroup(
            panelGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGTLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabeTituloGT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarGT)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGTLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panelGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRemplazoPE1)
                    .addGroup(panelGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGTLayout.createSequentialGroup()
                            .addComponent(jScrollPaneGT, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28))
                        .addGroup(panelGTLayout.createSequentialGroup()
                            .addComponent(jLabelEliminarGrupoGT)
                            .addGap(130, 130, 130)
                            .addComponent(btnEliminarGrupoGT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        panelGTLayout.setVerticalGroup(
            panelGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabeTituloGT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarGT))
                .addGap(38, 38, 38)
                .addComponent(jScrollPaneGT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(panelGTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEliminarGrupoGT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarGrupoGT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRemplazoPE1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPaneGTIA.addTab("Ver todos los grupos", panelGT);

        panelGI.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloGI.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloGI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloGI.setText("Administrador");

        jLabelProfesorGrupoGI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelProfesorGrupoGI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfesorGrupoGI.setText("Profesor:");

        jLabelNomProfesorGI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNomProfesorGI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelBuscarGrupoGI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelBuscarGrupoGI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscarGrupoGI.setText("Buscar grupo por grado:");

        jComboBoxGradoGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGradoGIActionPerformed(evt);
            }
        });

        jComboBoxGruposGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGruposGIActionPerformed(evt);
            }
        });

        btnCerrarGI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarGIbtnCerrarATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGILayout = new javax.swing.GroupLayout(panelGI);
        panelGI.setLayout(panelGILayout);
        panelGILayout.setHorizontalGroup(
            panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGILayout.createSequentialGroup()
                .addGroup(panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGILayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabelTituloGI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarGI))
                    .addGroup(panelGILayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneGI, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGILayout.createSequentialGroup()
                                .addGroup(panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelBuscarGrupoGI)
                                    .addComponent(jLabelProfesorGrupoGI))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelGILayout.createSequentialGroup()
                                        .addComponent(jComboBoxGradoGI, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxGruposGI, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelNomProfesorGI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGILayout.setVerticalGroup(
            panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTituloGI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarGI))
                .addGap(28, 28, 28)
                .addGroup(panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscarGrupoGI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGruposGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGradoGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProfesorGrupoGI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomProfesorGI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneGI, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPaneGTIA.addTab("Información de un grupo", panelGI);

        panelGA.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloGA.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloGA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloGA.setText("Administrador");

        btnCerrarSesionAdmin.setBackground(new java.awt.Color(153, 0, 0));
        btnCerrarSesionAdmin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCerrarSesionAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesionAdmin.setText("CERRAR SESION");
        btnCerrarSesionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionAdminActionPerformed(evt);
            }
        });

        jLabelElegirGradoGA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelElegirGradoGA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelElegirGradoGA.setText("Eligir un grado:");

        jComboBoxGradoGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGradoGAActionPerformed(evt);
            }
        });

        jLabelNombreGrupoGA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombreGrupoGA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreGrupoGA.setText("Nombre del grupo:");

        txtNombreGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreGrupoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreGrupoFocusLost(evt);
            }
        });
        txtNombreGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreGrupoActionPerformed(evt);
            }
        });

        btnGuardarGA.setBackground(new java.awt.Color(0, 0, 153));
        btnGuardarGA.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnGuardarGA.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarGA.setText("GUARDAR");
        btnGuardarGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarGAActionPerformed(evt);
            }
        });

        btnCerrarGA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarGAbtnCerrarATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGALayout = new javax.swing.GroupLayout(panelGA);
        panelGA.setLayout(panelGALayout);
        panelGALayout.setHorizontalGroup(
            panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGALayout.createSequentialGroup()
                .addGroup(panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGALayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabelTituloGA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                        .addComponent(btnCerrarGA))
                    .addGroup(panelGALayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardarGA, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGALayout.createSequentialGroup()
                                .addGroup(panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelElegirGradoGA)
                                    .addComponent(jLabelNombreGrupoGA))
                                .addGap(26, 26, 26)
                                .addGroup(panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxGradoGA, 0, 171, Short.MAX_VALUE)
                                    .addComponent(txtNombreGrupo))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrarSesionAdmin)
                .addGap(38, 38, 38))
        );
        panelGALayout.setVerticalGroup(
            panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloGA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarGA))
                .addGap(26, 26, 26)
                .addGroup(panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelElegirGradoGA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGradoGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreGrupoGA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarGA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(btnCerrarSesionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPaneGTIA.addTab("Agregar grupo", panelGA);

        jTabbedPaneAPG.addTab("Grupos", jTabbedPaneGTIA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAPG, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAPG)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnEliminarGrupoGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGrupoGTActionPerformed
        
        int[] filaSeleccionadas = tablaGT.table.getSelectedRows();

        for (int fila : filaSeleccionadas) {
            String grupo = tablaGT.table.getValueAt(fila, 0).toString();
            SentenciasSQL.bajaRegistro(grupo, "Grupo", "id_grupo");
        }
        setjBoxGrupos(jComboBoxGradoGI, jComboBoxGruposGI);
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/borrar.wav")));clip.start();}
        catch(Exception e){}
        this.actualizarTablas();
    }//GEN-LAST:event_btnEliminarGrupoGTActionPerformed

    private void jComboBoxGradoATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradoATActionPerformed
        this.setjBoxGrupos(jComboBoxGradoAT, jComboBoxGruposAT);
    }//GEN-LAST:event_jComboBoxGradoATActionPerformed

    private void btnBajaAlumnoATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaAlumnoATActionPerformed
        int[] filaSeleccionadas = tablaDatosAlumnos.table.getSelectedRows();
        for (int fila : filaSeleccionadas) {
            String alumno;
            alumno = tablaDatosAlumnos.table.getValueAt(fila, 0).toString();
            SentenciasSQL.bajaRegistro(alumno, "Alumno", "curp");
        }
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/borrar.wav")));clip.start();}
        catch(Exception e){}
        this.actualizarTablas();

    }//GEN-LAST:event_btnBajaAlumnoATActionPerformed

    private void btnEliminarADeGrupoATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarADeGrupoATActionPerformed

        int[] filaSeleccionadas = tablaDatosAlumnos.table.getSelectedRows();

        for (int fila : filaSeleccionadas) {
            tablaDatosAlumnos.table.setValueAt("", fila, 6);
        }
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/borrar.wav")));clip.start();}
        catch(Exception e){}
        this.actualizarTablas();
    }//GEN-LAST:event_btnEliminarADeGrupoATActionPerformed

    private void btnGuardarATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarATActionPerformed
        String obtener = jComboBoxGruposAT.getSelectedItem().toString();
        int[] filaSeleccionadas = tablaDatosAlumnos.table.getSelectedRows();
        for (int fila : filaSeleccionadas) {
            tablaDatosAlumnos.table.setValueAt(obtener, fila, 6);
        }
        
        this.actualizarTablas();

    }//GEN-LAST:event_btnGuardarATActionPerformed

    private void jComboBoxGruposATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGruposATActionPerformed

    }//GEN-LAST:event_jComboBoxGruposATActionPerformed

    private void jComboBoxGradoPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradoPTActionPerformed
        this.setjBoxGrupos(jComboBoxGradoPT, jComboBoxGruposPT);
    }//GEN-LAST:event_jComboBoxGradoPTActionPerformed

    private void jComboBoxGruposPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGruposPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGruposPTActionPerformed

    private void btnGuardarPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPTActionPerformed

        String obtener = jComboBoxGruposPT.getSelectedItem().toString();
        int[] filaSeleccionadas = tablaDatosProfesores.table.getSelectedRows();
        for (int fila : filaSeleccionadas) {
            tablaDatosProfesores.table.setValueAt(obtener, fila, 6);
        }
        this.actualizarTablas();
    }//GEN-LAST:event_btnGuardarPTActionPerformed

    private void btnEliminarPDeGrupoPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPDeGrupoPTActionPerformed

        int[] filaSeleccionadas = tablaDatosProfesores.table.getSelectedRows();

        for (int fila : filaSeleccionadas) {
            tablaDatosProfesores.table.setValueAt("", fila, 6);
        }
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/borrar.wav")));clip.start();}
        catch(Exception e){}
        this.actualizarTablas();
    }//GEN-LAST:event_btnEliminarPDeGrupoPTActionPerformed

    private void btnBajaProfesorPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaProfesorPTActionPerformed

        int[] filaSeleccionadas = tablaDatosProfesores.table.getSelectedRows();
        for (int fila : filaSeleccionadas) {
            String Profesor;
            Profesor = tablaDatosProfesores.table.getValueAt(fila, 0).toString();
            SentenciasSQL.bajaRegistro(Profesor, "Profesor", "rfc");
        }
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/borrar.wav")));clip.start();}
        catch(Exception e){}
        this.actualizarTablas();
    }//GEN-LAST:event_btnBajaProfesorPTActionPerformed

    private void jComboBoxGradoGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradoGIActionPerformed
        this.setjBoxGrupos(jComboBoxGradoGI, jComboBoxGruposGI);
    }//GEN-LAST:event_jComboBoxGradoGIActionPerformed

    private void jComboBoxGruposGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGruposGIActionPerformed

        String grupo="";
        try{
            grupo = "WHERE id_grupoFK='" + jComboBoxGruposGI.getSelectedItem().toString() + "'";
            actualizarLabelProfesor();
        }catch(Exception ex){
            jLabelNomProfesorGI.setText("No tiene profesor");
        }
            
        tablaGI = new TablaAdminGI(grupo);
        jScrollPaneGI.setViewportView(tablaGI.table);
    }//GEN-LAST:event_jComboBoxGruposGIActionPerformed

    private void btnCerrarSesionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionAdminActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar1.wav")));clip.start();}
            catch(Exception e){}
        JOptionPane.showMessageDialog(null,"SESION CERRADA.","EXITO",JOptionPane.INFORMATION_MESSAGE);
        
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionAdminActionPerformed

    private void jComboBoxGradoGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradoGAActionPerformed

    }//GEN-LAST:event_jComboBoxGradoGAActionPerformed

    private void txtNombreGrupoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreGrupoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGrupoFocusGained

    private void txtNombreGrupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreGrupoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGrupoFocusLost

    private void txtNombreGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGrupoActionPerformed

    private void btnGuardarGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGAActionPerformed
        String grado = jComboBoxGradoGA.getSelectedItem().toString();
        String grupo = txtNombreGrupo.getText();
        SentenciasSQL.agregarGrupo(grado, grupo);
        this.actualizarTablas();
    }//GEN-LAST:event_btnGuardarGAActionPerformed

    private void txtCurpATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpATActionPerformed

    private void txtCurpATKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpATKeyReleased
        tablaDatosAlumnos.getRowSorter().setRowFilter(RowFilter.regexFilter(txtCurpAT.getText(), 0));
        //Validaciones.setEstadoBoton(btnGuardarAT, tablaDatosAlumnos.table.getRowCount());
    }//GEN-LAST:event_txtCurpATKeyReleased

    private void txtRfcPTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRfcPTFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcPTFocusGained

    private void txtRfcPTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRfcPTFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcPTFocusLost

    private void txtRfcPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcPTActionPerformed

    private void txtRfcPTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcPTKeyReleased
        tablaDatosProfesores.getRowSorter().setRowFilter(RowFilter.regexFilter(txtRfcPT.getText(), 0));
        //Validaciones.setEstadoBoton(btnGuardarPT, tablaDatosProfesores.table.getRowCount());
    }//GEN-LAST:event_txtRfcPTKeyReleased

    private void btnCerrarATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarATActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarATActionPerformed

    private void btnCerrarPTbtnCerrarATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarPTbtnCerrarATActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarPTbtnCerrarATActionPerformed

    private void btnCerrarGTbtnCerrarATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarGTbtnCerrarATActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarGTbtnCerrarATActionPerformed

    private void btnCerrarGIbtnCerrarATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarGIbtnCerrarATActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarGIbtnCerrarATActionPerformed

    private void btnCerrarGAbtnCerrarATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarGAbtnCerrarATActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarGAbtnCerrarATActionPerformed
    //poner todos los grados en los comboBox
    public void setjBoxGrados() {
        ArrayList<Integer> grados = SentenciasSQL.consultarGrados();
        for (int g : grados) {
            
            jComboBoxGradoAT.addItem(String.valueOf(g));
            jComboBoxGradoPT.addItem(String.valueOf(g));
            jComboBoxGradoGI.addItem(String.valueOf(g));
            jComboBoxGradoGA.addItem(String.valueOf(g));
        }
    }

    //actualiza tablas
    public void actualizarTablas() {
        String grupoGI="";
        try{
            grupoGI = "WHERE id_grupoFK='" + jComboBoxGruposGI.getSelectedItem().toString() + "'";
        }catch(Exception ex){
            
        }
        //poner los grupos en los comboBox 
        this.setjBoxGrupos(jComboBoxGradoAT, jComboBoxGruposAT);
        this.setjBoxGrupos(jComboBoxGradoPT, jComboBoxGruposPT);
        //Inicializar todas las tablas
        tablaDatosAlumnos = new TablaAdminAlumno("");
        tablaDatosProfesores = new TablaAdminProfesor("");
        tablaGT = new TablaAdminGT();
        tablaGI = new TablaAdminGI(grupoGI);
        //ponerlas dentro de un panel
        jScrollPaneAT.setViewportView(tablaDatosAlumnos.table);
        jScrollPanePT.setViewportView(tablaDatosProfesores.table);
        jScrollPaneGT.setViewportView(tablaGT.table);
        jScrollPaneGI.setViewportView(tablaGI.table);
        actualizarLabelProfesor();
    }
    
    public void actualizarLabelProfesor(){
        String grupo = "";
        try {
            grupo = "WHERE id_grupoFK='" + jComboBoxGruposGI.getSelectedItem().toString() + "'";
            ArrayList<Profesor> prof = admin.todosProfesores(grupo);
            jLabelNomProfesorGI.setText(prof.get(0).getApPaterno()+" "+ prof.get(0).getApMaterno() +" " + prof.get(0).getNombres());
        } catch (Exception ex) {
            jLabelNomProfesorGI.setText("No tiene profesor");
        }
    }

    //actulizar Grupos de acuerdo al grado seleccionado
    public void setjBoxGrupos(JComboBox grado, JComboBox grupos) {
        String gradoSeleccionado = grado.getSelectedItem().toString();
        ArrayList<String> listaGrupos = admin.obternerGruposPorGrado(gradoSeleccionado);
        grupos.removeAllItems();
        for (String g : listaGrupos) {
            grupos.addItem(String.valueOf(g));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajaAlumnoAT;
    private javax.swing.JButton btnBajaProfesorPT;
    private javax.swing.JButton btnCerrarAT;
    private javax.swing.JButton btnCerrarGA;
    private javax.swing.JButton btnCerrarGI;
    private javax.swing.JButton btnCerrarGT;
    private javax.swing.JButton btnCerrarPT;
    private javax.swing.JButton btnCerrarSesionAdmin;
    private javax.swing.JButton btnEliminarADeGrupoAT;
    private javax.swing.JButton btnEliminarGrupoGT;
    private javax.swing.JButton btnEliminarPDeGrupoPT;
    private javax.swing.JButton btnGuardarAT;
    private javax.swing.JButton btnGuardarGA;
    private javax.swing.JButton btnGuardarPT;
    private javax.swing.JComboBox<String> jComboBoxGradoAT;
    private javax.swing.JComboBox<String> jComboBoxGradoGA;
    private javax.swing.JComboBox<String> jComboBoxGradoGI;
    private javax.swing.JComboBox<String> jComboBoxGradoPT;
    private javax.swing.JComboBox<String> jComboBoxGruposAT;
    private javax.swing.JComboBox<String> jComboBoxGruposGI;
    private javax.swing.JComboBox<String> jComboBoxGruposPT;
    private javax.swing.JLabel jLabeTituloGT;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabelAgregarAGrupoAT;
    private javax.swing.JLabel jLabelAgregarAGrupoPT;
    private javax.swing.JLabel jLabelAlumnoBajaAT;
    private javax.swing.JLabel jLabelBuscarElem;
    private javax.swing.JLabel jLabelBuscarElemAE1;
    private javax.swing.JLabel jLabelBuscarGrupoGI;
    private javax.swing.JLabel jLabelElegirGradoGA;
    private javax.swing.JLabel jLabelEliminarGrupoGT;
    private javax.swing.JLabel jLabelElminarADeGrupoAT;
    private javax.swing.JLabel jLabelElminarPDeGrupoPT;
    private javax.swing.JLabel jLabelNomProfesorGI;
    private javax.swing.JLabel jLabelNombreGrupoGA;
    private javax.swing.JLabel jLabelProfesorBajaPT;
    private javax.swing.JLabel jLabelProfesorGrupoGI;
    private javax.swing.JLabel jLabelRecuerdaAT;
    private javax.swing.JLabel jLabelRecuerdaPT;
    private javax.swing.JLabel jLabelRemplazoAT;
    private javax.swing.JLabel jLabelRemplazoPE1;
    private javax.swing.JLabel jLabelRemplazoPT;
    private javax.swing.JLabel jLabelTituloAT;
    private javax.swing.JLabel jLabelTituloGA;
    private javax.swing.JLabel jLabelTituloGI;
    private javax.swing.JLabel jLabelTituloPT;
    private javax.swing.JScrollPane jScrollPaneAT;
    private javax.swing.JScrollPane jScrollPaneGI;
    private javax.swing.JScrollPane jScrollPaneGT;
    private javax.swing.JScrollPane jScrollPanePT;
    private javax.swing.JTabbedPane jTabbedPaneAPG;
    private javax.swing.JTabbedPane jTabbedPaneGTIA;
    private javax.swing.JPanel panelAT;
    private javax.swing.JPanel panelGA;
    private javax.swing.JPanel panelGI;
    private javax.swing.JPanel panelGT;
    private javax.swing.JPanel panelPT;
    private javax.swing.JTextField txtCurpAT;
    private javax.swing.JTextField txtNombreGrupo;
    private javax.swing.JTextField txtRfcPT;
    // End of variables declaration//GEN-END:variables
}
