/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.sound.sampled.*;
/**
 *
 * @author lufer
 */
public class PerfilAlumno extends javax.swing.JFrame {

    //Esta variable es el usuario que ingreso, de ahi se obtienen los datos necesarios
    private Alumno usuario;
    TablaPerfilAlumno tablaCalificaciones;

    /**
     * Creates new form PerfilAlumno2
     */
    public PerfilAlumno() {
        initComponents();
    }

    public PerfilAlumno(Alumno usuario) {
        this.usuario = usuario;
        initComponents();
        tablaCalificaciones = new TablaPerfilAlumno(usuario, jComboBoxGrado.getSelectedItem().toString());
        jScrollPanelCalificaciones.setViewportView(tablaCalificaciones.table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelAlumno = new javax.swing.JTabbedPane();
        panelInformacion = new javax.swing.JPanel();
        jLabelTituloInformacion = new javax.swing.JLabel();
        jLabelTextNombre = new javax.swing.JLabel();
        jLabelTextCurp = new javax.swing.JLabel();
        jLabelTextEdad = new javax.swing.JLabel();
        jLabelTextGenero = new javax.swing.JLabel();
        jLabelTextGrupo = new javax.swing.JLabel();
        espacioNombre = new javax.swing.JLabel();
        espacioCurp = new javax.swing.JLabel();
        espacioEdad = new javax.swing.JLabel();
        espacioGrupo = new javax.swing.JLabel();
        espacioGenero = new javax.swing.JLabel();
        btnCerrarInformacion = new javax.swing.JButton();
        panelCalificaciones = new javax.swing.JPanel();
        jLabelTituloCalificaciones = new javax.swing.JLabel();
        jLabelTextoGrado = new javax.swing.JLabel();
        jComboBoxGrado = new javax.swing.JComboBox<>();
        jScrollPanelCalificaciones = new javax.swing.JScrollPane();
        btnCerrarCalificaciones = new javax.swing.JButton();
        panelConfiguracion = new javax.swing.JPanel();
        jLabelTituloConfiguracion = new javax.swing.JLabel();
        jLabelTextContrasena = new javax.swing.JLabel();
        btnCambiarContrasena = new javax.swing.JButton();
        btnCerrarSesionAlumno = new javax.swing.JButton();
        btnCerrarConfiguracion = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelInformacion.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloInformacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloInformacion.setText("Bienvenido alumno");

        jLabelTextNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextNombre.setText("Nombre completo:");

        jLabelTextCurp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextCurp.setText("CURP:");

        jLabelTextEdad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextEdad.setText("Edad:");

        jLabelTextGenero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextGenero.setText("Genero:");

        jLabelTextGrupo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextGrupo.setText("Grupo:");

        espacioNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        espacioNombre.setText(usuario.getNombres()+" "+usuario.getApPaterno()+" "+usuario.getApMaterno());

        espacioCurp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        espacioCurp.setText(usuario.getId());

        espacioEdad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        espacioEdad.setText(String.valueOf(usuario.getEdad()+" años")
        );

        espacioGrupo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        String grupo;
        try{
            if(usuario.getGrupo().equals("")){
                grupo = "No cuentas con un grupo asignado";
            }else{
                grupo = usuario.getGrupo();
            }
        }catch(Exception ex){
            grupo = "No cuentas con un grupo asignado";;
        }
        espacioGrupo.setText(grupo);

        espacioGenero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        espacioGenero.setText(String.valueOf(usuario.getGenero()));

        btnCerrarInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarInformacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarInformacion)
                .addGap(21, 21, 21))
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTextCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTextGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espacioCurp, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(espacioEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(espacioGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(espacioGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelTextNombre)
                        .addGap(18, 18, 18)
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTituloInformacion)
                            .addComponent(espacioNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTituloInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarInformacion))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextNombre)
                    .addComponent(espacioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addComponent(espacioCurp)
                        .addGap(18, 18, 18)
                        .addComponent(espacioEdad))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelTextCurp)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTextEdad)))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextGenero)
                    .addComponent(espacioGenero))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextGrupo)
                    .addComponent(espacioGrupo))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPanelAlumno.addTab("Información", panelInformacion);

        panelCalificaciones.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloCalificaciones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloCalificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloCalificaciones.setText("Bienvenido alumno");

        jLabelTextoGrado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextoGrado.setText("Grado:");

        ArrayList<Integer> grados = SentenciasSQL.consultarGrados();
        for (int g : grados) {
            jComboBoxGrado.addItem(String.valueOf(g));
        }
        jComboBoxGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGradoActionPerformed(evt);
            }
        });

        btnCerrarCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N

        javax.swing.GroupLayout panelCalificacionesLayout = new javax.swing.GroupLayout(panelCalificaciones);
        panelCalificaciones.setLayout(panelCalificacionesLayout);
        panelCalificacionesLayout.setHorizontalGroup(
            panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalificacionesLayout.createSequentialGroup()
                .addGroup(panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCalificacionesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTituloCalificaciones)
                        .addGap(108, 108, 108)
                        .addComponent(btnCerrarCalificaciones))
                    .addGroup(panelCalificacionesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPanelCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCalificacionesLayout.createSequentialGroup()
                                .addComponent(jLabelTextoGrado)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCalificacionesLayout.setVerticalGroup(
            panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalificacionesLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTituloCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarCalificaciones))
                .addGap(18, 18, 18)
                .addGroup(panelCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoGrado)
                    .addComponent(jComboBoxGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPanelCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPanelAlumno.addTab("Calificaciones", panelCalificaciones);

        panelConfiguracion.setBackground(new java.awt.Color(153, 153, 255));

        jLabelTituloConfiguracion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloConfiguracion.setText("Bienvenido alumno");

        jLabelTextContrasena.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextContrasena.setText("Contraseña:");

        btnCambiarContrasena.setBackground(new java.awt.Color(0, 0, 153));
        btnCambiarContrasena.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarContrasena.setText("CAMBIAR");
        btnCambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContrasenaActionPerformed(evt);
            }
        });

        btnCerrarSesionAlumno.setBackground(new java.awt.Color(153, 0, 0));
        btnCerrarSesionAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCerrarSesionAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesionAlumno.setText("CERRAR SESION");
        btnCerrarSesionAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionAlumnoActionPerformed(evt);
            }
        });

        btnCerrarConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cerrar.png"))); // NOI18N
        btnCerrarConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarConfiguracionbtnCerrarInformacionActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ojo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfiguracionLayout = new javax.swing.GroupLayout(panelConfiguracion);
        panelConfiguracion.setLayout(panelConfiguracionLayout);
        panelConfiguracionLayout.setHorizontalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabelTituloConfiguracion)
                .addGap(123, 123, 123)
                .addComponent(btnCerrarConfiguracion)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTextContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesionAlumno))
                .addGap(52, 52, 52))
        );
        panelConfiguracionLayout.setVerticalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTituloConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarConfiguracion))
                .addGap(18, 18, 18)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTextContrasena)
                            .addComponent(btnCambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(254, 254, 254))
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnCerrarSesionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPanelAlumno.addTab("Configuración", panelConfiguracion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelAlumno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelAlumno)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradoActionPerformed
        tablaCalificaciones = new TablaPerfilAlumno(usuario, jComboBoxGrado.getSelectedItem().toString());
        jScrollPanelCalificaciones.setViewportView(tablaCalificaciones.table);
    }//GEN-LAST:event_jComboBoxGradoActionPerformed

    private void btnCambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContrasenaActionPerformed
        String contra = txtContrasena.getText();
        System.out.println(contra);
        usuario.setContrasena(contra, "Alumno", "curp");

    }//GEN-LAST:event_btnCambiarContrasenaActionPerformed
    //Cierra la sesion mandando a Inicio
    private void btnCerrarSesionAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionAlumnoActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar1.wav")));clip.start();}
            catch(Exception e){}
        JOptionPane.showMessageDialog(null,"SESION CERRADA.","EXITO",JOptionPane.INFORMATION_MESSAGE);
        
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionAlumnoActionPerformed

    private void btnCerrarConfiguracionbtnCerrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarConfiguracionbtnCerrarInformacionActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarConfiguracionbtnCerrarInformacionActionPerformed

    private void btnCerrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarInformacionActionPerformed
        try{Clip clip=AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/media/Cerrar2.wav")));clip.start();}
        catch(Exception e){}
        JOptionPane.showMessageDialog(null,"HASTA LUEGO.","CERRAR",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnCerrarInformacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtContrasena.echoCharIsSet()){txtContrasena.setEchoChar((char)0);}
        else{txtContrasena.setEchoChar('*');}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarContrasena;
    private javax.swing.JButton btnCerrarCalificaciones;
    private javax.swing.JButton btnCerrarConfiguracion;
    private javax.swing.JButton btnCerrarInformacion;
    private javax.swing.JButton btnCerrarSesionAlumno;
    private javax.swing.JLabel espacioCurp;
    private javax.swing.JLabel espacioEdad;
    private javax.swing.JLabel espacioGenero;
    private javax.swing.JLabel espacioGrupo;
    private javax.swing.JLabel espacioNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxGrado;
    private javax.swing.JLabel jLabelTextContrasena;
    private javax.swing.JLabel jLabelTextCurp;
    private javax.swing.JLabel jLabelTextEdad;
    private javax.swing.JLabel jLabelTextGenero;
    private javax.swing.JLabel jLabelTextGrupo;
    private javax.swing.JLabel jLabelTextNombre;
    private javax.swing.JLabel jLabelTextoGrado;
    private javax.swing.JLabel jLabelTituloCalificaciones;
    private javax.swing.JLabel jLabelTituloConfiguracion;
    private javax.swing.JLabel jLabelTituloInformacion;
    private javax.swing.JScrollPane jScrollPanelCalificaciones;
    private javax.swing.JTabbedPane jTabbedPanelAlumno;
    private javax.swing.JPanel panelCalificaciones;
    private javax.swing.JPanel panelConfiguracion;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables

    public Person getUsuario() {
        return usuario;
    }

    public void setUsuario(Alumno usuario) {
        this.usuario = usuario;
    }
}
